### ISSUE TITLE
I am only getting 6 steps following the setup in the busybeaver.txt file

### ISSUE THREAD

**Issue by Beniled** [0xdanelia/regex_turing_machine#1]
I click "Replace" 7 times and then it halts. 
Here is a screenshot.

Find: ^!0([01]{20})([01])([01]*\r\n\[ +\^\r\n#)(.*)\r\n(?=(.*\r\n)*^>\4\.\2:([01])((0)|1)(.*\r\n))
Replace: !\8\8\1\6\3\9

![image](https://user-images.githubusercontent.com/20345999/155199348-e0ca43d3-53c3-4124-9b1a-7f9a6e7b1653.png)

Notepad++ V8.2.1

**Comment by Beniled** [comment]
HUH... Ok so you HAVE to have a  newline after the last instruction. So I had to have 16 rows. 

When I added the blank line after 15 it worked.... Might want to add a note to the instructions.

![image](https://user-images.githubusercontent.com/20345999/155200661-cdc8b1e4-b438-4cb6-baaa-b7f46db00628.png)

**Comment by 0xdanelia** [comment]
Thanks for the report. I added a note in the README to address this.

**Comment by AlexanderYastrebov** [comment]
Also hit this issue while copy-pasting, maybe its worth adding "Make sure to add at least one newline after your instruction set" or "Copy this line as well" into the busybeaver.txt itself :)

I can also confirm it works on Ubuntu Linux in `gedit` editor using modified `\n`-only regexp `^!0([01]{20})([01])([01]*\n\[ +\^\n#)(.*)\n(?=(.*\n)*^>\4\.\2:([01])((0)|1)(.*\n))` and holding spacebar on `Replace All` after clicking `Find` once.

![Screenshot from 2022-02-23 03-36-21](https://user-images.githubusercontent.com/697976/155253215-6e02d3c1-1a81-461e-bef8-160aee174304.png)
